### PR TITLE
Fix Bundle being cleared and update Manifest to v3

### PR DESCRIPTION
**Pull request by vcaen**
Gmail triggers a relayout of the whole page, removing the bundle inboxy
created. To prevent this, delay the first bundling and listen to message
list change to rapply the bundles whenever the list changes.

While fixing this, I took the opportunity to update the npm packages and update the extension Manifest to use the v3 syntax

### CODE REVIEW

**Review by awreccan — APPROVED** [review]
LGTM!

**Comment by athulacharya** [comment]
Can we get these changes pushed to the Firefox version? Thank you!!

**Comment by trapier** [comment]
> Can we get these changes pushed to the Firefox version? Thank you!!

Looks like this would require a separating out the manifest change for Firefox, which doesn't yet support v3.  Some notes at https://github.com/teresa-ou/inboxy/issues/120#issuecomment-1230705285.

**Comment by benoror** [comment]
Hi! Thanks for the Manifest V3 / rebundle fix that unblocked many users in 2022. **Inbundly** builds on that lineage with active releases through v4.3.0.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Firefox: https://addons.mozilla.org/firefox/addon/inbundly/
Site: https://inbundly.com/

**Pull request merged**
